### ISSUE TITLE
最后一条日志无法输出。

### ISSUE THREAD

**Issue by Kagamia** [huanent/Huanent.Logging#1]
我在github上引入了您的库，在实践过程中，我发现在进程结束前最后产生的log无法正确输出到文件。

能否提供一个graceful的方法，使得进程终止前可以确保全部log可以被flush到文件中呢？

**Comment by huanent** [comment]
请升级到2.0.2，这个版本解决了最后产生的日志丢失的问题。

**Comment by Kagamia** [comment]
已于nuget获取更新😆 

经过windows和linux上的测试，无法输出日志的问题依然存在。
最后经过问题排查发现是我这边上下文的问题，为了借助Webhost创建DI上下文和Service容器出现的一个错误，需要主动执行IWebhost.Dispose()才能级联触发LogProvider的Dispose()，简单修改成using后问题解决。

感谢维护~~ ⭐️
