### ISSUE TITLE
按照了Huanent.Logging.File

### ISSUE THREAD

**Issue by Japesy** [huanent/Huanent.Logging#2]
在Program 添加以下内容，要引用哪些命名空间，Huanent.Logging.File这个命名空间无法using .谢谢
 public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
   手动高亮  --> .ConfigureLogging(builder => builder.AddFile()) 
                .Build();

**Comment by huanent** [comment]
@Japesy Microsoft.Extensions.Logging 引用这个命名空间即可，vs在Program文件夹里面的引用智能提示有bug不能显示using提示
