### ISSUE TITLE
文档中的LogLevel的warning写错了

### ISSUE THREAD

**Issue by zzliujianbo** [huanent/Huanent.Logging#3]
你好，很感谢你提供了这么好的日志框架。

在阅读文档过程中，发现有一处写错了。

**原文**
`手动高亮  -->    "Default": "Wanring" //具体输入级别自行修改，也可添加详细的分类别输出`

`Wanring` 中的`n`和`r`写反了。应为`Warning`

**Comment by zzliujianbo** [comment]
还有项目描述

**原文**
```
microsoft.extensions.logging日子组件拓展
```

`日子`应为`日志`

**Comment by huanent** [comment]
@zzliujianbo 感谢提醒，谢谢

**Comment by huanent** [comment]
已修正
