### ISSUE TITLE
worker service 中记录tcp 读取流记录了两遍

### ISSUE THREAD

**Issue by jcntec** [huanent/Huanent.Logging#6]
public class Worker : BackgroundService
    {
        public static Worker Instance { get; set; }

        private readonly ILogger<Worker> _logger;
        private readonly IConfiguration _configuration;
        private TcpClient TcpClient;

        public Worker(ILogger<Worker> logger, IConfiguration configuration)
        {
            Instance = this;
            _logger = logger;
            _configuration = configuration;
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            _logger.LogWarning("启动");

            try
            {
                if (string.IsNullOrWhiteSpace(_configuration["HostComputer:Server:port"]) || _configuration["HostComputer:Server:port"] == "0")
                    return;

                TcpListener tcpListener = new TcpListener(System.Net.IPAddress.Any, Convert.ToInt32(_configuration["HostComputer:Server:port"]));
                tcpListener.Start();
                _logger.LogInformation("开始监听：" + _configuration["HostComputer:Server:port"]);
                while (true)
                {
                    TcpClient = await tcpListener.AcceptTcpClientAsync();

                    Listener(TcpClient);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.ToString());
            }

            //stoppingToken.WaitHandle.WaitOne();
        }

        private async void Listener(TcpClient client)
        {
            TcpClient = client;

            var stream = client.GetStream();
            var count = 0;
            do
            {
                try
                {
                    var bytes = default(byte[]);
                    var buffer = new byte[3];

                    var offset = 0;

                    while (offset < 3)
                    {
                        using CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(60000);
                        using (cancellationTokenSource.Token.Register(() => client.Client.Shutdown(SocketShutdown.Receive)))
                        {
                            try
                            {
                                offset += count = await stream.ReadAsync(buffer, offset, 3 - offset, cancellationTokenSource.Token);
                            }
                            catch (Exception)
                            {
                                count = 0;
                            }
                        }
                        if (count == 0)
                            break;
                    }

                    bytes = buffer.ToArray();

                    if (bytes[0] != 0x5A && bytes[1] != 0xA5)
                    {
                        _logger.LogError("指令头错误：" + BitConverter.ToString(new byte[] { bytes[0], bytes[1] }));
                        break;
                    }
                    var length = bytes[2];
                    if (length == 0)
                    {
                        _logger.LogError("长度为0");
                        break;
                    }
                    buffer = new byte[length - 3];

                    offset = 0;

                    while (offset < length - 3)
                    {
                        using CancellationTokenSource cancellationTokenSource = new CancellationTokenSource(60000);
                        using (cancellationTokenSource.Token.Register(() => client.Client.Shutdown(SocketShutdown.Receive)))
                        {
                            try
                            {
                                offset += count = await stream.ReadAsync(buffer, offset, length - 3 - offset, cancellationTokenSource.Token);
                            }
                            catch (Exception)
                            {
                                count = 0;
                            }
                        }
                        if (count == 0)
                            break;
                    }

                    var bytesList = bytes.ToList();
                    bytesList.AddRange(buffer.ToArray());

                    bytes = bytesList.ToArray();

                    _logger.LogWarning("IP:" + (client.Client.RemoteEndPoint).ToString() + " 收到数据：" + BitConverter.ToString(bytes.ToArray()));//两遍记录

日志文件：

-----2021/09/29 13:59:18-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-06-FF
-----End-----

-----2021/09/29 13:59:18-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-07-FF
-----End-----

-----2021/09/29 13:59:18-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-06-FF
-----End-----

-----2021/09/29 13:59:18-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-07-FF
-----End-----

-----2021/09/29 14:00:08-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-06-FF
-----End-----

-----2021/09/29 14:00:08-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-06-FF
-----End-----

-----2021/09/29 14:00:08-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-07-FF
-----End-----

-----2021/09/29 14:00:08-----
Warning:WebManager.Worker
IP:192.168.1.100:49153 收到数据：5A-A5-05-07-FF
-----End-----

**Comment by ricklan2020** [comment]
有并发写的问题，已提PR

**Comment by huanent** [comment]
> 有并发写的问题，已提PR

已合并👍
